package com.superwall.sdk.kmp

import com.superwall.sdk.kmp.models.entitlements.CustomerInfo
import com.superwall.sdk.kmp.models.entitlements.SubscriptionStatus
import com.superwall.sdk.kmp.models.events.SuperwallEventInfo
import com.superwall.sdk.kmp.models.options.LogLevel
import com.superwall.sdk.kmp.models.options.LogScope
import com.superwall.sdk.kmp.models.paywall.PaywallInfo
import com.superwall.sdk.kmp.models.redemption.RedemptionResult

/**
 * The delegate protocol that handles Superwall lifecycle events.
 *
 * The delegate methods receive callbacks from the SDK in response to certain placements.
 *
 * You set this via [Superwall.delegate]. Every method has a default no-op
 * implementation, so override only the ones you need.
 *
 * ## Threading
 *
 * Callbacks arrive on the thread the underlying native SDK invoked them on —
 * this layer adds no dispatch of its own, so a high-volume hook like
 * [handleLog] can never cost you frames. In practice that means:
 *
 * - The **paywall lifecycle** hooks ([willPresentPaywall], [didPresentPaywall],
 *   [willDismissPaywall], [didDismissPaywall], [handleCustomPaywallAction],
 *   [paywallWillOpenURL], [paywallWillOpenDeepLink]) arrive on the **main
 *   thread** on both platforms — both native SDKs emit them from their UI
 *   layer. Update UI from these directly.
 * - The **analytics-shaped** hooks ([handleSuperwallEvent], [handleLog],
 *   [subscriptionStatusDidChange], [customerInfoDidChange],
 *   [userAttributesDidChange], [willRedeemLink], [didRedeemLink]) arrive on a
 *   **background thread on Android** and on the main thread on iOS. Forward
 *   them to your analytics SDK as-is; if you need to touch UI, hop yourself
 *   (`withContext(Dispatchers.Main) {... }`), or collect
 *   [Superwall.subscriptionStatusFlow] / [Superwall.customerInfoFlow] in a
 *   main-dispatched scope instead, which handles the hop for you.
 *
 * Two consequences worth designing for: implementations should be
 * **thread-safe** (the analytics hooks are not serialized against each other),
 * and they run **synchronously on an SDK thread** — blocking in one slows the
 * SDK, so keep them short and hand long work to your own scope.
 *
 * To learn how to conform to the delegate in your app and best practices, see
 * [our docs](https://docs.superwall.com/docs/3rd-party-analytics).
 */
public interface SuperwallDelegate {
    /**
     * Called when the subscription status of [Superwall] changes.
     *
     * @param from The previous subscription status.
     * @param to The new subscription status.
     */
    public fun subscriptionStatusDidChange(
        from: SubscriptionStatus,
        to: SubscriptionStatus,
    ) {}

    /**
     * Called whenever an internal analytics placement is tracked.
     *
     * @param eventInfo Information about the tracked event.
     */
    public fun handleSuperwallEvent(eventInfo: SuperwallEventInfo) {}

    /**
     * Called when the user taps an element on your paywall with a custom action.
     *
     * @param name The name of the custom action.
     */
    public fun handleCustomPaywallAction(name: String) {}

    /**
     * Called right before the paywall is dismissed.
     *
     * @param paywallInfo Information about the paywall being dismissed.
     */
    public fun willDismissPaywall(paywallInfo: PaywallInfo) {}

    /**
     * Called right before the paywall is presented.
     *
     * @param paywallInfo Information about the paywall being presented.
     */
    public fun willPresentPaywall(paywallInfo: PaywallInfo) {}

    /**
     * Called right after the paywall is dismissed.
     *
     * @param paywallInfo Information about the dismissed paywall.
     */
    public fun didDismissPaywall(paywallInfo: PaywallInfo) {}

    /**
     * Called right after the paywall is presented.
     *
     * @param paywallInfo Information about the presented paywall.
     */
    public fun didPresentPaywall(paywallInfo: PaywallInfo) {}

    /**
     * Called when the user opens a URL with a specific tag on your paywall.
     *
     * @param url The URL being opened.
     */
    public fun paywallWillOpenURL(url: String) {}

    /**
     * Called when the user taps a deep link in your paywall.
     *
     * @param url The deep link URL being opened.
     */
    public fun paywallWillOpenDeepLink(url: String) {}

    /**
     * Receive all log messages generated by the SDK.
     *
     * Unmappable native level/scope strings fall back to [LogLevel.DEBUG] /
     * [LogScope.ALL], with the raw string preserved under `info["rawLevel"]` /
     * `info["rawScope"]`.
     *
     * @param level The log level of the message.
     * @param scope The scope of the SDK that produced the message.
     * @param message The log message, if any.
     * @param info Additional structured information attached to the log entry.
     * @param error A description of the error that triggered the log, if any.
     */
    public fun handleLog(
        level: LogLevel,
        scope: LogScope,
        message: String?,
        info: Map<String, Any?>?,
        error: String?,
    ) {}

    /**
     * Called before the redemption of a code from a web paywall.
     */
    public fun willRedeemLink() {}

    /**
     * Called after a code was redeemed from a web paywall.
     *
     * @param result The result of the redemption.
     */
    public fun didRedeemLink(result: RedemptionResult) {}

    /**
     * Called after handling a Superwall deep link with the format
     * `yoursubdomain.superwall.app/app-link/...`.
     *
     * @platform iOS (Android: pending upstream support in superwall-android).
     *
     * @param fullURL The full deep link URL.
     * @param pathComponents The path components of the URL after `app-link`.
     * @param queryParameters The query parameters of the URL.
     */
    public fun handleSuperwallDeepLink(
        fullURL: String,
        pathComponents: List<String>,
        queryParameters: Map<String, String>,
    ) {}

    /**
     * Called when the customer info of [Superwall] changes.
     *
     * @platform iOS (Android: pending upstream support in superwall-android).
     *
     * @param from The previous customer info.
     * @param to The new customer info.
     */
    public fun customerInfoDidChange(
        from: CustomerInfo,
        to: CustomerInfo,
    ) {}

    /**
     * Called when user attributes change.
     *
     * @param newAttributes The updated user attributes.
     */
    public fun userAttributesDidChange(newAttributes: Map<String, Any?>) {}
}
